apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
        - image: worker_service
          name: worker-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  type: LoadBalancer
  ports:
    - port: 8087
  selector:
    app: worker-app